import React from 'react'
import Head from 'next/head' 

function head() {
    return (
        <Head>
            <title>User Random Company App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default head